name: Conditions_check

on:
  push:
    branches:
      - main
      - feature/*

jobs:
  conditions-check-on-main:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: condition on main
        run: echo "Deploying the changes to Procuction"

  condition-check-on-feature:
    if: startswith(github.ref, 'refs/heads/feature/')
    runs-on: ubuntu-latest
    steps:
      - name: condition check on feature
        run: echo "Running feature validation"
