name: Date Output

on:
  workflow_dispatch:

jobs:
  capture-date:
    runs-on: ubuntu-latest
    outputs:
      shared-date: ${{ steps.set-date.outputs.today }}
    steps:
      - id: set-date
        run: echo "today=$(date)" >> $GITHUB_OUTPUT

  show-output:
    runs-on: ubuntu-latest
    needs: capture-date
    steps:
      - name: read the captured output
        run: echo "Date recieved - ${{ needs.capture-date.outputs.shared-date}}"
