name: Reusable Deploy Workflow

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
        default: dev
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy step
        run: |
          if [[ "${{ inputs.env }}" != "dev" && "${{ inputs.env }}" != "sit" && "${{ inputs.env }}" != "uat" ]]; then
          echo "Invalid Environment"
          exit 1
          else
          echo "Starting Deployment..."
          echo "Deploying to ${{ inputs.env }}"
          fi
