name: matrix strategy

on:
  workflow_dispatch:

jobs:
  multi-env-deploy:
    strategy:
      fail-fast: false
      matrix:
        env: [dev, sit, uat]
    runs-on: ubuntu-latest
    steps:
      - name: deploy to ${{ matrix.env }} Environment
        run: |
          echo "Starting Deployment..."
          echo "Deploying to - ${{ matrix.env }}"
