name: matrix strategy

on:
  workflow_dispatch:

jobs:
  multi-env-deploy:
    strategy:
      matrix:
        env: [dev, sit, uat]
    runs-on: ubuntu-latest
    steps:
      - name: deploy to all env
        run: echo "Deploying to ${{ matrix.env }}"
