name: Salesforce PR Validation

on:
  pull_request:
    types:
      - "opened"
      - "synchronize"
      - "reopened"
    branches: [main]

jobs:
  validate-deployment:
    if: ${{ startsWith(github.head_ref, 'feature/' )}}
    runs-on: ubuntu-latest

    env:
      ORG: SIT

    steps:
      #1. Code Checkout
      - name: Code Checkout
        uses: actions/checkout@v6

      #2. Install CLI
      - name: Install Salesforce CLI
        run: |
          npm install -g @salesforce/cli
          sf --version

      #3. Create JWT Key File
      - name: Create JWT Key File
        run: |
          echo "${{ secrets.SF_JWT_KEY }}" > jwt-key.txt
          chmod 600 jwt-key.txt

      #4. Authenticate Credentials using JWT
      - name: Authenticate to Salesforce
        run: |
          sf org login jwt \
           --client-id ${{ secrets.SF_CLIENT_ID }} \
           --jwt-key-file jwt-key.txt \
           --username ${{ secrets.SF_USERNAME }} \
           --instance-url ${{ secrets.SF_INSTANCE_URL }} \
           --alias Zensar

      #5. Verify Org Connection
      - name: Verify Org
        run: |
          sf org display --target-org Zensar

      #6. Validate Deployment
      - name: Validate deployment
        run: |
          echo "Triggered from Branch: ${{ github.head_ref }}"
          echo "Target Org: $ORG"
          sf project deploy start \
            --manifest force-app/manifest/minipackage.xml \
            --target-org Zensar \
