name: Salesforce PR Validation

on:
  pull_request:
    types:
      - "opened"
      - "synchronize"
      - "reopened"
    branches: [main]

jobs:
  validate-deployment:
    if: ${{ startsWith(github.head_ref, 'feature/' )}}
    runs-on: [self-hosted]

    env:
      ORG: SIT

    steps:
      #1. Code Checkout
      - name: Code Checkout
        uses: actions/checkout@v6

      #2. Setup Node
      - name: Setup Node js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      #3. Install CLI
      - name: Install Salesforce CLI
        run: |
          npm install -g @salesforce/cli
          sf --version

      #4. Create JWT Key File
      - name: Create JWT Key File
        run: |
          echo "${{ secrets.SF_JWT_KEY }}" > jwt-key.txt
          chmod 600 jwt-key.txt

      #5. Authenticate Credentials using JWT
      - name: Authenticate to Salesforce
        run: |
          sf org login jwt \
           --client-id ${{ secrets.SF_CLIENT_ID }} \
           --jwt-key-file jwt-key.txt \
           --username ${{ secrets.SF_USERNAME }} \
           --instance-url ${{ secrets.SF_INSTANCE_URL }} \
           --alias Zensar

      #6. Verify Org Connection
      - name: Verify Org
        run: |
          sf org display --target-org Zensar

      #7. Validate Deployment
      - name: Validate deployment
        run: |
          echo "Triggered from Branch: ${{ github.head_ref }}"
          echo "Target Org: $ORG"
          sf project deploy start \
            --manifest force-app/manifest/minipackage.xml \
            --target-org Zensar \

      #8. Clean up Job
      - name: Clean Up the Job
        if: always()
        run: |
          rm -rf ~/.sf
          rm -rf ~/.npm
