name: salesforce validation

on:
  pull_request:
    branches: [main]

jobs:
  validate-deployment:
    runs-on: ubuntu-latest
    steps:
      #1. Checkout code
      - name: Code Checkout
        uses: actions/checkout@v6

      #2. Install Salesforce CLI
      - name: Install Salesforce CLI
        run: npm install @salesforce/cli --global

      #3. Verify CLI Installation
      - name: Verify CLI
        run: sf --version

      #4. Mock Authentication
      - name: Authentication to salesforce
        run: echo "Authenticating to salesforc org.."

      # 5. Validate Deployment (Check-Only)
      - name: Validate Deployment
        run: |
          echo "Triggered from branch: ${{ github.head_ref }}"
          echo "Running check-only deployment..."
          echo "Validating metadata in force-app..."
